### ISSUE TITLE
可以单独开关某个插件的吗？

### ISSUE THREAD

**Issue by cs571393** [didi/echo#11]
因为网络请求导致有些视图慢了释放，一直弹出内存泄露的提示

**Comment by cocoa-chen** [comment]
可以通过指定加载特定的插件，如
pod 'EchoSDK', :configurations => ["Debug"], :subspecs => ['Basic', 'MockGPS', 'Network', 'Notification', 'Notification', 'ViewBorder', 'Watchdog', 'Crash', 'NSUserDefaults']
目前支持的插件列表是：'Basic', 'MockGPS', 'Network', 'Notification', 'Notification', 'ViewBorder', 'Watchdog', 'Crash', 'NSUserDefaults', 'GeneralLog', 'MemoryLeak'

**Comment by cs571393** [comment]
好的👌我来试试

**Comment by cs571393** [comment]
@cocoa-chen
 [!] CocoaPods could not find compatible versions for pod "EchoSDK/Basic":
  In Podfile:
    EchoSDK/Basic

None of your spec sources contain a spec satisfying the dependency: `EchoSDK/Basic`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by cocoa-chen** [comment]
pod 'EchoSDK', :configurations => ["Debug"], :subspecs => ['Plugins/Basic', 'Plugins/MockGPS', 'Plugins/Network', 'Plugins/Notification', 'Plugins/Notification', 'Plugins/ViewBorder', 'Plugins/Watchdog', 'Plugins/Crash', 'Plugins/NSUserDefaults']
不好意思，刚才发错了，忘发Plugins前缀了，你用这个再试下

**Comment by cs571393** [comment]
[!] The subspecs of `EchoSDK` are linked to different build configurations for the `Pods-Konvy` target. CocoaPods does not currently support subspecs across different build configurations.

**Comment by cocoa-chen** [comment]
1.在podfile里去掉 :configurations => ["Debug"]再pod install是可以的
2.加载全部插件，不想用的手动将对应的ECOXXXPlugin的+load方法注释掉

**Comment by cs571393** [comment]
@cocoa-chen 我用了第二种方法可以了。因为我只是要在debug下使用
