### ISSUE TITLE
Xcode 12.0 beta 5  有个奔溃问题

### ISSUE THREAD

**Issue by Rookie-liu** [didi/echo#14]
### 首先感谢
感谢滴滴大佬开源了一款这么好用的工具, 在我们开发使用起来真的非常的方便.

### 目前的问题 
在使用 `xcode 11 `的时候没有任何问题 , 更新到`Xcode 12.0 beta 5 `版本后 . 使用的时候发生奔溃. 最后根据定位发现问题出现在` ECOnetServiceBrowser` 这个里面,  
![WX20200907-115500.png-923.7kB][1]

![WechatIMG311.png-957.2kB][2]

发现是一直在进行失败重新启动 resetBrowserService
如果注释掉` [self resetBrowserService];` 就没有了崩溃现象, 但是 echo 中也没有了查看网络请求的功能, 由于技术能力有限, 实在不知道问题出现在哪里.

### 期望
希望滴滴大佬在百忙之中能注意下这个问题, 看能否给与解决一下.

  [1]: http://static.zybuluo.com/Rookie/t81bd8v8re0v4xcgkj4qb4p7/WX20200907-115500.png
  [2]: http://static.zybuluo.com/Rookie/82nyh7pb1qvpkccjeicotvum/WechatIMG311.png

**Comment by cocoa-chen** [comment]
你好，我拿beta 4还没稳定复现，等更新下Xcode再看看，感谢反馈

**Comment by Rookie-liu** [comment]
> 你好，我拿beta 4还没稳定复现，等更新下Xcode再看看，感谢反馈

好的  辛苦大佬

**Comment by cocoa-chen** [comment]
你好，我更新到新版Xcode后复现了该问题。原因是iOS14系统对本地网络权限进行了限制，需要在工程的Info.plist文件中添加NSLocalNetworkUsageDescription和NSBonjourServices配置。在Xcode中选中Info.plist文件，右键选择Open As Source Code，并添加如下内容

```
<key>NSLocalNetworkUsageDescription</key>
<string></string>
<key>NSBonjourServices</key>
<array>
	<string>_ECHO._tcp</string>
</array>
```

新版本的tag已解决崩溃问题，正在推Specs，后续更新到新版本也可以解决崩溃问题

**Comment by Rookie-liu** [comment]
> 你好，我更新到新版Xcode后复现了该问题。原因是iOS14系统对本地网络权限进行了限制，需要在工程的Info.plist文件中添加NSLocalNetworkUsageDescription和NSBonjourServices配置。在Xcode中选中Info.plist文件，右键选择Open As Source Code，并添加如下内容
> 
> ```
> <key>NSLocalNetworkUsageDescription</key>
> <string></string>
> <key>NSBonjourServices</key>
> <array>
> 	<string>_ECHO._tcp</string>
> </array>
> ```
> 
> 新版本的tag已解决崩溃问题，正在推Specs，后续更新到0.0.6版本也可以解决崩溃问题

感谢老板对问题的关注以及对版本的更新和维护, 问题以及解决, issue 可以关闭了 .
