### ISSUE TITLE
Xcode12 、真机iOS14状态下崩溃

### ISSUE THREAD

**Issue by a714857512** [didi/echo#15]
![image](https://user-images.githubusercontent.com/14026494/93428866-c343dc80-f8f2-11ea-9fe0-5052d8c0c657.png)

Xcode12 、真机iOS14状态下崩溃在
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [[ECOCoreManager shared] sendPacketData:data type:type plugin:plugin toDevice:device];
    });

//发送数据
- (void)plugin:(__kindof ECOBasePlugin *)plugin willSendData:(id)data type:(ECOPacketDataType)type toDevice:(ECOChannelDeviceInfo *)device {
//    NSLog(@"<<[ECOPluginsManager] %@ plugin sendData:%@", plugin.pluginName, data);
    //封装数据
    if (!data) {
        return;
    }
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [[ECOCoreManager shared] sendPacketData:data type:type plugin:plugin toDevice:device];
    });
}

**Comment by cocoa-chen** [comment]
> ![image](https://user-images.githubusercontent.com/14026494/93428866-c343dc80-f8f2-11ea-9fe0-5052d8c0c657.png)
> 
> Xcode12 、真机iOS14状态下崩溃在
> dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
> [[ECOCoreManager shared] sendPacketData:data type:type plugin:plugin toDevice:device];
> });
> 
> //发送数据
> 
> * (void)plugin:(__kindof ECOBasePlugin *)plugin willSendData:(id)data type:(ECOPacketDataType)type toDevice:(ECOChannelDeviceInfo *)device {
>   //    NSLog(@"<<[ECOPluginsManager] %@ plugin sendData:%@", plugin.pluginName, data);
>   //封装数据
>   if (!data) {
>   return;
>   }
>   dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
>   [[ECOCoreManager shared] sendPacketData:data type:type plugin:plugin toDevice:device];
>   });
>   }

由于iOS14系统本地网络权限限制，需要在工程的Info.plist文件中添加NSLocalNetworkUsageDescription和NSBonjourServices配置。在Xcode中选中Info.plist文件，右键选择Open As Source Code，并添加如下内容

`<key>NSLocalNetworkUsageDescription</key>
<string></string>
<key>NSBonjourServices</key>
<array>
	<string>_ECHO._tcp</string>
</array>`

新版本的tag已解决崩溃问题，正在推Specs
