### ISSUE TITLE
如何使用部分插件？我不希望启动一些我不用的插件

### ISSUE THREAD

**Issue by xyhuangjia** [didi/echo#19]

**Comment by cocoa-chen** [comment]
有两种方式:
1、可以通过指定加载特定的插件，如pod 'EchoSDK', :subspecs => ['Plugins/Basic', 'Plugins/MockGPS', 'Plugins/Network', 'Plugins/Notification', 'Plugins/Notification', 'Plugins/ViewBorder', 'Plugins/Watchdog', 'Plugins/Crash', 'Plugins/NSUserDefaults']，但记得上线打包前要注释掉该依赖
2、不想用的手动将对应的ECOXXXPlugin的+load方法注释掉
