### ISSUE TITLE
网络请求无法看到入参

### ISSUE THREAD

**Issue by shengguangdaren** [didi/echo#4]
项目中引入框架试了下，刷新界面网络请求只能看到出参，看不到body入参,并且清空日志的时候只能清空每次网络请求，下边的`Request``Response`均无法清空

**Comment by cocoa-chen** [comment]
Mac端请更新到最新代码后运行，客户端集成时请使用最新版SDK来解决该问题。集成方式为
pod 'EchoSDK', '0.0.2'
