### ISSUE TITLE
集成之后崩溃

### ISSUE THREAD

**Issue by simpleLiYu** [didi/echo#5]
<img width="930" alt="QQ20200407-155717@2x" src="https://user-images.githubusercontent.com/20043672/78644473-835edf00-78e8-11ea-9222-ec7ac17609bd.png">

**Comment by cocoa-chen** [comment]
@simpleLiYu hello，请问你工程的Podfile里开启use_frameworks!了吗？Podfile里设置的最低版本是多少？

**Comment by HanksHu** [comment]
这个是xcod11.3的问题，xcode真机调试的时候，禁止用第三方framework。把use_frameworks!换成 use_modular_headers!，就好了。
不过我的手机升级到iOS13.4，xcode 升级到11.4后已经没有这个问题了。可以参考这个https://www.jianshu.com/p/e59a386d2b43

**Comment by simpleLiYu** [comment]
> 这个是xcod11.3的问题，xcode真机调试的时候，禁止使用第三方框架。把use_frameworks！换成use_modular_headers !，就好了。
> 不过我的手机升级到iOS13.4，xcode升级到11.4后已经没有这个问题了。可以参考这个https://www.jianshu.com/p/e59a386d2b43

我的Xcode是11.4的，模拟器调试的，模拟器Xs Max 12.2版本的有这个问题

**Comment by simpleLiYu** [comment]
> @simpleLiYu你好，请问你工程的Podfile里开启use_frameworks！了吗？Podfile里设置的最低版本是多少？
你好，配置如图，Xcode是11.4的，模拟器调试的，模拟器Xs Max 12.2版本的有问题，试了别的模拟器好像也有。前几天用还是好的，昨天试了下腾讯的linkin发现没这个好用换回来重新pod install 之后出现的问题。感谢大佬开源的强大工具，麻烦你有空重新试下谢谢
<img width="487" alt="QQ20200408-114534@2x" src="https://user-images.githubusercontent.com/20043672/78742393-7b597a80-798e-11ea-9680-5e255734130b.png">

**Comment by simpleLiYu** [comment]
> @simpleLiYu hello，请问你工程的Podfile里开启use_frameworks!了吗？Podfile里设置的最低版本是多少？
参考这个https://www.jianshu.com/p/4759e2083719，删除DerivedData之后OK了
---------------------------------------------------------------------------------
麻烦问下echo的崩溃文件如何访问，崩溃日志的file path能否加上复制功能

**Comment by HanksHu** [comment]
我用我的电脑试了下，可以正常集成、运行。
- Xcode：Version 11.4 (11E146)。
- 模拟机是xs max， iOS 13.0
- 真机：iOS13.4.1，iPhone XR。
```
target 'EchoSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'EchoSDK'
  # Pods for EchoSDKDemo
  
end

```

**Comment by cocoa-chen** [comment]
> > @simpleLiYu hello，请问你工程的Podfile里开启use_frameworks!了吗？Podfile里设置的最低版本是多少？
> > 参考这个[https://www.jianshu.com/p/4759e2083719，删除DerivedData之后OK了](https://www.jianshu.com/p/4759e2083719%EF%BC%8C%E5%88%A0%E9%99%A4DerivedData%E4%B9%8B%E5%90%8EOK%E4%BA%86)
> 
> 麻烦问下echo的崩溃文件如何访问，崩溃日志的file path能否加上复制功能

崩溃信息可以从底部的详情区复制出来，file path的复制功能待会我加一下，加完之后可以从Finder中查看

**Comment by cocoa-chen** [comment]
> > @simpleLiYu hello，请问你工程的Podfile里开启use_frameworks!了吗？Podfile里设置的最低版本是多少？
> > 参考这个[https://www.jianshu.com/p/4759e2083719，删除DerivedData之后OK了](https://www.jianshu.com/p/4759e2083719%EF%BC%8C%E5%88%A0%E9%99%A4DerivedData%E4%B9%8B%E5%90%8EOK%E4%BA%86)
> 
> 麻烦问下echo的崩溃文件如何访问，崩溃日志的file path能否加上复制功能

你好，file path的复制功能已添加，更新下Mac端最新代码重新run一下就可以了

**Comment by simpleLiYu** [comment]
> 我用我的电脑试了下，可以正常集成，运行。
> 
> * Xcode：版本11.4（11E146）。
> * 模拟机是xs max，iOS 13.0
> * 真机：iOS13.4.1，iPhone XR。
> 
> ```
> target 'EchoSDKDemo' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   use_frameworks!
>   pod 'EchoSDK'
>   # Pods for EchoSDKDemo
>   
> end
> ```
恩，删除了DerivedData之后可以正常运行了，感谢

**Comment by simpleLiYu** [comment]
> > > @simpleLiYu你好，请问你工程的Podfile里打开use_frameworks！了吗？Podfile里设置的最低版本是多少？
> > > 参考这个[https://www.jianshu.com/p/4759e2083719，删除DerivedData之后OK了](https://www.jianshu.com/p/4759e2083719%EF%BC%8C%E5%88%A0%E9%99%A4DerivedData%E4%B9%8B%E5%90%8EOK%E4%BA%86)
> > 
> > 
> > 麻烦问下echo的崩溃文件如何访问，崩溃日志的文件路径是否具有复制功能
> 
> 你好，文件路径的复制功能已添加，更新下Mac端最新代码重新运行一下就可以了

好的，十分感谢
