### ISSUE TITLE
为什么不用Swift呢

### ISSUE THREAD

**Issue by HanksHu** [didi/echo#6]
请问下，既然这个项目是新的，为啥不用Swift呢。毕竟swift写起来比OC舒服多了，语法也有更多特性。

**Comment by cocoa-chen** [comment]
在启动做这个项目的时候，滴滴工程的构建工具还没有做Swift的接入工作。为了更快更方便的在我们的工程里跑起来，当初选项还是用的OC。我一般做和公司项目没有强关联的工具时会采用Swift开发，其他情况还是OC为主

**Comment by HanksHu** [comment]
😄不过Swift是趋势，还是更希望用Swift。
