### ISSUE TITLE
网络阻塞问题

### ISSUE THREAD

**Issue by DDfans** [didi/echo#7]
项目中有图片视频上传的操作，这些操作会导致app网络阻塞，所有网络请求全部超时，必须重新启动app才能恢复。
网络断开时Mac端会打印日志
Log content：
-[ECONetServiceBrowser netServiceDidStop:]

**Comment by zhanghe8** [comment]
能给一下导致网络阻塞的图片视频上传操作部分的主要代码吗？我们尝试复现一下

**Comment by cocoa-chen** [comment]
你好，请更新到最新版本再试下。集成方式为
pod 'EchoSDK', '0.0.3', :configurations => ["Debug"]

**Comment by DDfans** [comment]
nice，问题解决了~

**Comment by ChuanWSwist** [comment]
@cocoa-chen 弱弱的问一句，集成SDK到APP中会影响应用审核吗

**Comment by cocoa-chen** [comment]
> @cocoa-chen 弱弱的问一句，集成SDK到APP中会影响应用审核吗

不会影响。但是建议只在Debug模式下调试使用，别带到线上
